name: pulse_frontend
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  http: ^0.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
